apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: juphc-tc-pipeline-run-
spec:
  pipelineRef:
    name: juphc-tc-pipeline
  params:
    - name: build-image
      value: us.icr.io/sn-labs-boitshokosoomo/juphc-tax-calculator
    - name: repo-url
      value: https://github.com/BoitshokoSoomo/juphc-tc_pipeline.git
    - name: branch
      value: main
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipelinerun-pvc
    - name: dockerconfig-ws
      secret:
        secretName: icr
